language: python
python: "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo add-apt-repository ppa:pylab/stable -y  # For SciPY
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-tz
  - sudo apt-get install -qq python-scipy
  - sudo apt-get install -qq python-pastescript
  - sudo apt-get install -qq python-babel
  - sudo apt-get install -qq python-webob
  - sudo apt-get install -qq python-weberror
install:
  - pip install isodate  # For Biryani1 datetimeconv
  - pip install -e git+https://github.com/etalab/biryani.git@biryani1#egg=Biryani1  # For OpenFisca-Core
  - pip install -e git+https://github.com/openfisca/openfisca-core.git#egg=OpenFisca-Core
  - pip install -e git+https://github.com/openfisca/openfisca-france.git#egg=OpenFisca-France
  - pip install -r requirements.txt
script:
  - python /usr/bin/paster serve development.ini &
  - sleep 5
  - nosetests openfisca_web_api/tests
